title: Mineral Physics Group

logo: /assets/img/MPG.jpg

description: A special interest group of the <a href="https://www.minersoc.org/">Mineralogical Society of the UK and Ireland</a>. <br/>
                <br/>
                {% include RiP2026_link.html %}
                {% include Previous_RiPs_link.html %}

   
show_downloads: false

google_analytics: G-T9RKX0S41B

theme: jekyll-theme-minimal

plugins:
  - jekyll-github-metadata
