title: Mineral Physics Group

logo: /assets/img/MPG.jpg

description: A special interest group of the <a href="https://www.minersoc.org/">Mineralogical Society of the UK and Ireland</a>. <br/>
                <br/>
                <a href="{{ '/RiP_2026/RiP_2026.html' | relative_url }}">💎 RiP 2026 meeting</a><br/>
                <a href="{{ '/previous_RiP_meetings.html' | relative_url }}">💎 Previous RiP meetings</a><br/>

   
show_downloads: false

google_analytics: G-T9RKX0S41B

theme: jekyll-theme-minimal

plugins:
  - jekyll-github-metadata
